version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: screamerr/kittygram-backend:latest
    command: gunicorn kittygram_backend.wsgi:application --bind 0:8081  # Привязываем gunicorn к порту 8081
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8081"
    env_file:
      - ./.env
    depends_on:
      - db


  frontend:
    image: screamerr/kittygram-frontend:latest
    command: npm run build
    volumes:
      - static_volume:/app/build/static
    depends_on:
      - backend

  gateway:
    image: screamerr/kittygram-gateway:latest
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_volume:
  media_volume:
