version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "9000:8000"
    volumes:
      - media:/app/kittygram_media
      - static:/app/kittygram_static
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - static:/app/static
    env_file:
      - .env

  gateway:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - kittygram_media:/app/media
      - kittygram_static_volumes:/app/static

volumes:
  pg_data:
  static:
  media:
