version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: your-dockerhub-username/kittygram-backend:latest  # Замените на имя вашего образа
    command: gunicorn kittygram_backend.wsgi:application --bind 0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    image: your-dockerhub-username/kittygram-frontend:latest  # Замените на имя вашего образа
    command: npm run build
    volumes:
      - static_volume:/app/build/static
    depends_on:
      - backend

  gateway:
    image: your-dockerhub-username/kittygram-gateway:latest  # Замените на имя вашего образа
    ports:
      - "9000:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_volume:
  media_volume:
