version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "9000:8000"
    volumes:
      - static:/var/www/kittygram/static
      - media:/var/www/kittygram/media
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - static:/var/www/kittygram/static
    env_file:
      - .env

  gateway:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/var/www/kittygram/static
      - media:/var/www/kittygram/media

volumes:
  pg_data:
  static:
  media:
